# -*- coding: utf-8 -*-
"""Salary_Estimation_LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfJFoPPs3hD2xZbS0KISDwRi8GDHsHs1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression





salary = pd.read_csv("Salary Data.csv")

salary.info()

salary.head()

salary.describe()

sns.displot(salary['Salary'])

salary.dropna(inplace=True)
salary.drop_duplicates(inplace=True)

salary = pd.get_dummies(salary, columns=['Gender', 'Education Level', 'Job Title'], drop_first=True)

X = salary.drop(['Salary'], axis=1)
y = salary['Salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

lm = LinearRegression()
lm.fit(X_train, y_train)

print("Linear Regression Model Trained Successfully!")

trained_feature_names = X_train.columns.tolist()
print(trained_feature_names)

# Collect input data for a new individual
input_age = float(input("Enter the Age:"))
input_gender = input("Enter the Gender:")
input_education_level = input("Enter the Education Level:")
input_job_title = input("Enter the Job Title:")
input_years_of_experience = float(input("Enter the Experience:"))

# Preprocess the input data to match the training format
input_data = pd.DataFrame({
    'Age': [input_age],
    'Gender_Male': [1 if input_gender == 'Male' else 0],
    'Gender_Female': [1 if input_gender == 'Female' else 0],
    'Education Level_Bachelor\'s': [1 if input_education_level == "Bachelor's" else 0],
    'Education Level_Master\'s': [1 if input_education_level == "Master's" else 0],
    'Education Level_PhD': [1 if input_education_level == "PhD" else 0],
    # for Job titles
    'Job Title_Software Engineer': [1 if input_job_title == 'Software Engineer' else 0],
    'Job Title_Accountant': [1 if input_job_title == 'Accountant' else 0],
    'Job Title_Administrative Assistant': [1 if input_job_title == 'Administrative Assistant' else 0],
    'Job Title_Business Analyst': [1 if input_job_title == 'Business Analyst' else 0],
    'Job Title_Business Development Manager': [1 if input_job_title == 'Business Development Manager' else 0],
    'Job Title_Business Intelligence Analyst': [1 if input_job_title == 'Business Intelligence Analyst' else 0],
    'Job Title_CEO': [1 if input_job_title == 'CEO' else 0],
    'Job Title_Chief Data Officer': [1 if input_job_title == 'Chief Data Officer' else 0],
    'Job Title_Chief Technology Officer': [1 if input_job_title == 'Chief Technology Officer' else 0],
    'Job Title_Content Marketing Manager': [1 if input_job_title == 'Content Marketing Manager' else 0],
    'Job Title_Copywriter': [1 if input_job_title == 'Copywriter' else 0],
    'Job Title_Creative Director': [1 if input_job_title == 'Creative Director' else 0],
    'Job Title_Customer Service Manager': [1 if input_job_title == 'Customer Service Manager' else 0],
    'Job Title_Customer Service Rep': [1 if input_job_title == 'Customer Service Rep' else 0],
    'Job Title_Customer Service Representative': [1 if input_job_title == 'Customer Service Representative' else 0],
    'Job Title_Customer Success Manager': [1 if input_job_title == 'Customer Success Manager' else 0],
    'Job Title_Customer Success Rep': [1 if input_job_title == 'Customer Success Rep' else 0],
    'Job Title_Data Analyst': [1 if input_job_title == 'Data Analyst' else 0],
    'Job Title_Data Entry Clerk': [1 if input_job_title == 'Data Entry Clerk' else 0],
    'Job Title_Data Scientist': [1 if input_job_title == 'Data Scientist' else 0],
    'Job Title_Digital Content Producer': [1 if input_job_title == 'Digital Content Producer' else 0],
    'Job Title_Digital Marketing Manager': [1 if input_job_title == 'Digital Marketing Manager' else 0],
    'Job Title_Director': [1 if input_job_title == 'Director' else 0],
    'Job Title_Director of Business Development': [1 if input_job_title == 'Director of Business Development' else 0],
    'Job Title_Director of Engineering': [1 if input_job_title == 'Director of Engineering' else 0],
    'Job Title_Director of Finance': [1 if input_job_title == 'Director of Finance' else 0],
    'Job Title_Director of HR': [1 if input_job_title == 'Director of HR' else 0],
    'Job Title_Director of Human Capital': [1 if input_job_title == 'Director of Human Capital' else 0],
    'Job Title_Director of Human Resources': [1 if input_job_title == 'Director of Human Resources' else 0],
    'Job Title_Director of Marketing': [1 if input_job_title == 'Director of Marketing' else 0],
    'Job Title_Director of Operations': [1 if input_job_title == 'Director of Operations' else 0],
    'Job Title_Director of Product Management': [1 if input_job_title == 'Director of Product Management' else 0],
    'Job Title_Director of Sales': [1 if input_job_title == 'Director of Sales' else 0],
    'Job Title_Director of Sales and Marketing': [1 if input_job_title == 'Director of Sales and Marketing' else 0],
    'Job Title_Event Coordinator': [1 if input_job_title == 'Event Coordinator' else 0],
    'Job Title_Financial Advisor': [1 if input_job_title == 'Financial Advisor' else 0],
    'Job Title_Financial Analyst': [1 if input_job_title == 'Financial Analyst' else 0],
    'Job Title_Financial Manager': [1 if input_job_title == 'Financial Manager' else 0],
    'Job Title_Graphic Designer': [1 if input_job_title == 'Graphic Designer' else 0],
    'Job Title_HR Generalist': [1 if input_job_title == 'HR Generalist' else 0],
    'Job Title_HR Manager': [1 if input_job_title == 'HR Manager' else 0],
    'Job Title_Help Desk Analyst': [1 if input_job_title == 'Help Desk Analyst' else 0],
    'Job Title_Human Resources Director': [1 if input_job_title == 'Human Resources Director' else 0],
    'Job Title_IT Manager': [1 if input_job_title == 'IT Manager' else 0],
    'Job Title_IT Support': [1 if input_job_title == 'IT Support' else 0],
    'Job Title_IT Support Specialist': [1 if input_job_title == 'IT Support Specialist' else 0],
    'Job Title_Junior Account Manager': [1 if input_job_title == 'Junior Account Manager' else 0],
    'Job Title_Junior Accountant': [1 if input_job_title == 'Junior Accountant' else 0],
    'Job Title_Junior Advertising Coordinator': [1 if input_job_title == 'Junior Advertising Coordinator' else 0],
    'Job Title_Junior Business Analyst': [1 if input_job_title == 'Junior Business Analyst' else 0],
    'Job Title_Junior Business Development Associate': [1 if input_job_title == 'Junior Business Development Associate' else 0],
    'Job Title_Junior Business Operations Analyst': [1 if input_job_title == 'Junior Business Operations Analyst' else 0],
    'Job Title_Junior Copywriter': [1 if input_job_title == 'Junior Copywriter' else 0],
    'Job Title_Junior Customer Support Specialist': [1 if input_job_title == 'Junior Customer Support Specialist' else 0],
    'Job Title_Junior Data Analyst': [1 if input_job_title == 'Junior Data Analyst' else 0],
    'Job Title_Junior Data Scientist': [1 if input_job_title == 'Junior Data Scientist' else 0],
    'Job Title_Junior Designer': [1 if input_job_title == 'Junior Designer' else 0],
    'Job Title_Junior Developer': [1 if input_job_title == 'Junior Developer' else 0],
    'Job Title_Junior Financial Advisor': [1 if input_job_title == 'Junior Financial Advisor' else 0],
    'Job Title_Junior Financial Analyst': [1 if input_job_title == 'Junior Financial Analyst' else 0],
    'Job Title_Junior HR Coordinator': [1 if input_job_title == 'Junior HR Coordinator' else 0],
    'Job Title_Junior HR Generalist': [1 if input_job_title == 'Junior HR Generalist' else 0],
    'Job Title_Junior Marketing Analyst': [1 if input_job_title == 'Junior Marketing Analyst' else 0],
    'Job Title_Junior Marketing Coordinator': [1 if input_job_title == 'Junior Marketing Coordinator' else 0],
    'Job Title_Junior Marketing Manager': [1 if input_job_title == 'Junior Marketing Manager' else 0],
    'Job Title_Junior Marketing Specialist': [1 if input_job_title == 'Junior Marketing Specialist' else 0],
    'Job Title_Junior Operations Analyst': [1 if input_job_title == 'Junior Operations Analyst' else 0],
    'Job Title_Junior Operations Coordinator': [1 if input_job_title == 'Junior Operations Coordinator' else 0],
    'Job Title_Junior Operations Manager': [1 if input_job_title == 'Junior Operations Manager' else 0],
    'Job Title_Junior Product Manager': [1 if input_job_title == 'Junior Product Manager' else 0],
    'Job Title_Junior Project Manager': [1 if input_job_title == 'Junior Project Manager' else 0],
    'Job Title_Junior Recruiter': [1 if input_job_title == 'Junior Recruiter' else 0],
    'Job Title_Junior Research Scientist': [1 if input_job_title == 'Junior Research Scientist' else 0],
    'Job Title_Junior Sales Representative': [1 if input_job_title == 'Junior Sales Representative' else 0],
    'Job Title_Junior Social Media Manager': [1 if input_job_title == 'Junior Social Media Manager' else 0],
    'Job Title_Junior Social Media Specialist': [1 if input_job_title == 'Junior Social Media Specialist' else 0],
    'Job Title_Junior Software Developer': [1 if input_job_title == 'Junior Software Developer' else 0],
    'Job Title_Junior Software Engineer': [1 if input_job_title == 'Junior Software Engineer' else 0],
    'Job Title_Junior UX Designer': [1 if input_job_title == 'Junior UX Designer' else 0],
    'Job Title_Junior Web Designer': [1 if input_job_title == 'Junior Web Designer' else 0],
    'Job Title_Junior Web Developer': [1 if input_job_title == 'Junior Web Developer' else 0],
    'Job Title_Marketing Analyst': [1 if input_job_title == 'Marketing Analyst' else 0],
    'Job Title_Marketing Coordinator': [1 if input_job_title == 'Marketing Coordinator' else 0],
    'Job Title_Marketing Manager': [1 if input_job_title == 'Marketing Manager' else 0],
    'Job Title_Marketing Specialist': [1 if input_job_title == 'Marketing Specialist' else 0],
    'Job Title_Network Engineer': [1 if input_job_title == 'Network Engineer' else 0],
    'Job Title_Office Manager': [1 if input_job_title == 'Office Manager' else 0],
    'Job Title_Operations Analyst': [1 if input_job_title == 'Operations Analyst' else 0],
    'Job Title_Operations Director': [1 if input_job_title == 'Operations Director' else 0],
    'Job Title_Operations Manager': [1 if input_job_title == 'Operations Manager' else 0],
    'Job Title_Principal Engineer': [1 if input_job_title == 'Principal Engineer' else 0],
    'Job Title_Principal Scientist': [1 if input_job_title == 'Principal Scientist' else 0],
    'Job Title_Product Designer': [1 if input_job_title == 'Product Designer' else 0],
    'Job Title_Product Manager': [1 if input_job_title == 'Product Manager' else 0],
    'Job Title_Product Marketing Manager': [1 if input_job_title == 'Product Marketing Manager' else 0],
    'Job Title_Project Engineer': [1 if input_job_title == 'Project Engineer' else 0],
    'Job Title_Project Manager': [1 if input_job_title == 'Project Manager' else 0],
    'Job Title_Public Relations Manager': [1 if input_job_title == 'Public Relations Manager' else 0],
    'Job Title_Recruiter': [1 if input_job_title == 'Recruiter' else 0],
    'Job Title_Research Director': [1 if input_job_title == 'Research Director' else 0],
    'Job Title_Research Scientist': [1 if input_job_title == 'Research Scientist' else 0],
    'Job Title_Sales Associate': [1 if input_job_title == 'Sales Associate' else 0],
    'Job Title_Sales Director': [1 if input_job_title == 'Sales Director' else 0],
    'Job Title_Sales Executive': [1 if input_job_title == 'Sales Executive' else 0],
    'Job Title_Sales Manager': [1 if input_job_title == 'Sales Manager' else 0],
    'Job Title_Sales Operations Manager': [1 if input_job_title == 'Sales Operations Manager' else 0],
    'Job Title_Sales Representative': [1 if input_job_title == 'Sales Representative' else 0],
    'Job Title_Senior Account Executive': [1 if input_job_title == 'Senior Account Executive' else 0],
    'Job Title_Senior Account Manager': [1 if input_job_title == 'Senior Account Manager' else 0],
    'Job Title_Senior Accountant': [1 if input_job_title == 'Senior Accountant' else 0],
    'Job Title_Senior Business Analyst': [1 if input_job_title == 'Senior Business Analyst' else 0],
    'Job Title_Senior Business Development Manager': [1 if input_job_title == 'Senior Business Development Manager' else 0],
    'Job Title_Senior Consultant': [1 if input_job_title == 'Senior Consultant' else 0],
    'Job Title_Senior Data Analyst': [1 if input_job_title == 'Senior Data Analyst' else 0],
    'Job Title_Senior Data Engineer': [1 if input_job_title == 'Senior Data Engineer' else 0],
    'Job Title_Senior Data Scientist': [1 if input_job_title == 'Senior Data Scientist' else 0],
    'Job Title_Senior Engineer': [1 if input_job_title == 'Senior Engineer' else 0],
    'Job Title_Senior Financial Advisor': [1 if input_job_title == 'Senior Financial Advisor' else 0],
    'Job Title_Senior Financial Analyst': [1 if input_job_title == 'Senior Financial Analyst' else 0],
    'Job Title_Senior Financial Manager': [1 if input_job_title == 'Senior Financial Manager' else 0],
    'Job Title_Senior Graphic Designer': [1 if input_job_title == 'Senior Graphic Designer' else 0],
    'Job Title_Senior HR Generalist': [1 if input_job_title == 'Senior HR Generalist' else 0],
    'Job Title_Senior HR Manager': [1 if input_job_title == 'Senior HR Manager' else 0],
    'Job Title_Senior HR Specialist': [1 if input_job_title == 'Senior HR Specialist' else 0],
    'Job Title_Senior Human Resources Coordinator': [1 if input_job_title == 'Senior Human Resources Coordinator' else 0],
    'Job Title_Senior Human Resources Manager': [1 if input_job_title == 'Senior Human Resources Manager' else 0],
    'Job Title_Senior Human Resources Specialist': [1 if input_job_title == 'Senior Human Resources Specialist' else 0],
    'Job Title_Senior IT Consultant': [1 if input_job_title == 'Senior IT Consultant' else 0],
    'Job Title_Senior IT Project Manager': [1 if input_job_title == 'Senior IT Project Manager' else 0],
    'Job Title_Senior IT Support Specialist': [1 if input_job_title == 'Senior IT Support Specialist' else 0],
    'Job Title_Senior Marketing Analyst': [1 if input_job_title == 'Senior Marketing Analyst' else 0],
    'Job Title_Senior Manager': [1 if input_job_title == 'Senior Manager' else 0],
    'Job Title_Senior Marketing Coordinator': [1 if input_job_title == 'Senior Marketing Coordinator' else 0],
    'Job Title_Senior Marketing Director': [1 if input_job_title == 'Senior Marketing Director' else 0],
    'Job Title_Senior Marketing Manager': [1 if input_job_title == 'Senior Marketing Manager' else 0],
    'Job Title_Senior Marketing Specialist': [1 if input_job_title == 'Senior Marketing Specialist' else 0],
    'Job Title_Senior Operations Analyst': [1 if input_job_title == 'Senior Operations Analyst' else 0],
    'Job Title_Senior Operations Coordinator': [1 if input_job_title == 'Senior Operations Coordinator' else 0],
    'Job Title_Senior Operations Manager': [1 if input_job_title == 'Senior Operations Manager' else 0],
    'Job Title_Senior Product Designer': [1 if input_job_title == 'Senior Product Designer' else 0],
    'Job Title_Senior Product Development Manager': [1 if input_job_title == 'Senior Product Development Manager' else 0],
    'Job Title_Senior Product Manager': [1 if input_job_title == 'Senior Product Manager' else 0],
    'Job Title_Senior Product Marketing Manager': [1 if input_job_title == 'Senior Product Marketing Manager' else 0],
    'Job Title_Senior Project Coordinator': [1 if input_job_title == 'Senior Project Coordinator' else 0],
    'Job Title_Senior Project Manager': [1 if input_job_title == 'Senior Project Manager' else 0],
    'Job Title_Senior Quality Assurance Analyst': [1 if input_job_title == 'Senior Quality Assurance Analyst' else 0],
    'Job Title_Senior Research Scientist': [1 if input_job_title == 'Senior Research Scientist' else 0],
    'Job Title_Senior Researcher': [1 if input_job_title == 'Senior Researcher' else 0],
    'Job Title_Senior Sales Manager': [1 if input_job_title == 'Senior Sales Manager' else 0],
    'Job Title_Senior Sales Representative': [1 if input_job_title == 'Senior Sales Representative' else 0],
    'Job Title_Senior Scientist': [1 if input_job_title == 'Senior Scientist' else 0],
    'Job Title_Senior Software Architect': [1 if input_job_title == 'Senior Software Architect' else 0],
    'Job Title_Senior Software Developer': [1 if input_job_title == 'Senior Software Developer' else 0],
    'Job Title_Senior Software Engineer': [1 if input_job_title == 'Senior Software Engineer' else 0],
    'Job Title_Senior Training Specialist': [1 if input_job_title == 'Senior Training Specialist' else 0],
    'Job Title_Senior UX Designer': [1 if input_job_title == 'Senior UX Designer' else 0],
    'Job Title_Social Media Manager': [1 if input_job_title == 'Social Media Manager' else 0],
    'Job Title_Social Media Specialist': [1 if input_job_title == 'Social Media Specialist' else 0],
    'Job Title_Software Developer': [1 if input_job_title == 'Software Developer' else 0],
    'Job Title_Software Manager': [1 if input_job_title == 'Software Manager' else 0],
    'Job Title_Software Project Manager': [1 if input_job_title == 'Software Project Manager' else 0],
    'Job Title_Strategy Consultant': [1 if input_job_title == 'Strategy Consultant' else 0],
    'Job Title_Supply Chain Analyst': [1 if input_job_title == 'Supply Chain Analyst' else 0],
    'Job Title_Supply Chain Manager': [1 if input_job_title == 'Supply Chain Manager' else 0],
    'Job Title_Technical Recruiter': [1 if input_job_title == 'Technical Recruiter' else 0],
    'Job Title_Technical Support Specialist': [1 if input_job_title == 'Technical Support Specialist' else 0],
    'Job Title_Technical Writer': [1 if input_job_title == 'Technical Writer' else 0],
    'Job Title_Training Specialist': [1 if input_job_title == 'Training Specialist' else 0],
    'Job Title_UX Designer': [1 if input_job_title == 'UX Designer' else 0],
    'Job Title_UX Researcher': [1 if input_job_title == 'UX Researcher' else 0],
    'Job Title_VP of Finance': [1 if input_job_title == 'VP of Finance' else 0],
    'Job Title_VP of Operations': [1 if input_job_title == 'VP of Operations' else 0],
    'Job Title_Web Developer': [1 if input_job_title == 'Web Developer' else 0],
    'Years of Experience': [input_years_of_experience]
})

# Ensure the feature order matches the one used for training
input_data = input_data[X_train.columns]

# Make predictions for the input data
predicted_salary = lm.predict(input_data)

# Print the predicted salary
print("Predicted Salary for Input Data:", predicted_salary[0])

from sklearn import metrics
predictions = lm.predict(X_test)
mse = metrics.mean_squared_error(y_test,predictions)
mse

plt.scatter(y_test, predictions, c='red', label='Actual')
plt.scatter(y_test, y_test, c='blue', label='Predicted')

plt.xlabel("Actual values")
plt.ylabel("Predicted values")
plt.title("Predicted versus actual values (MSE={:.2f})".format(mse))
plt.legend()
plt.title("Predicted versus actual values (MSE={:.2f})".format(mse))

print("Model Score", lm.score(X_test, y_test)*100)

print('r2 : ', metrics.r2_score(predictions, y_test)*100)